/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package session08_Design;

import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Ex03_Login extends javax.swing.JFrame {

    Connection cnn;

    PreparedStatement st;
    ResultSet rs;
    DefaultTableModel model;
    Locale viLocale, usLocale;
    ResourceBundle currentBundle, viBundle, usBundle;
    Vector tmp;
    int insert = 0;

    /**
     * Creates new form Ex03_Login
     */
    public Ex03_Login() {
        initComponents();
        cnn = DBConnect.makeConnection();
        model = new DefaultTableModel();

        String[] cols = {"username", "password"};
        model.setColumnIdentifiers(cols);
        loadData();
        viLocale = new Locale("vi", "VN");
        usLocale = new Locale("en", "US");
        viBundle = ResourceBundle.getBundle("session08_Design/login_vi_VN", viLocale);
        usBundle = ResourceBundle.getBundle("session08_Design/login_en_US", usLocale);
    }

    void display() {
        mnFile.setText(currentBundle.getString("mnFile"));
        mnExit.setText(currentBundle.getString("mnExit"));
        mnLanguage.setText(currentBundle.getString("mnLanguage"));
        mnUS.setText(currentBundle.getString("mnUS"));
        mnVN.setText(currentBundle.getString("mnVN"));
        lblFmTitle.setText(currentBundle.getString("lblFrmTitle"));
        rdUS.setText(currentBundle.getString("rdUS"));
        rdVN.setText(currentBundle.getString("rdVN"));
        lblUsername.setText(currentBundle.getString("lblUsername"));
        lblPassword.setText(currentBundle.getString("lblPassword"));
        btnLogin.setText(currentBundle.getString("btnLogin"));
        btnLogout.setText(currentBundle.getString("btnLogout"));
        btnRegister.setText(currentBundle.getString("btnRegister"));
        btnConfirm.setText(currentBundle.getString("btnConfirm"));
    }

//    boolean checkLogin() {
//        String username = txtUsername.getText().trim();
//        String password = txtPassword.getText().trim();
//
//        if (model.getRowCount() > 0) {
//            for (int i = 0; i < model.getRowCount(); i++) {
//                if (username.equals(model.getValueAt(i, 0)) || password.equals(model.getValueAt(i, 1))) {
//                    return true;
//                }
//            }
//        }
//        return false;
//    }
    private boolean checkLogin(String name, String password) {
        String query = "select * from [user] where username = ? and password = ?";
        try {
            st = cnn.prepareStatement(query);
            st.setString(1, name);
            st.setString(2, password);
            rs = st.executeQuery();
            if (rs.next()) {
                return true;
            }
        } catch (SQLException e) {
            e.getMessage();
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLanguage = new javax.swing.ButtonGroup();
        lblFmTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rdUS = new javax.swing.JRadioButton();
        rdVN = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        cBox = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItem = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        mnBar = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnExit = new javax.swing.JMenuItem();
        mnLanguage = new javax.swing.JMenu();
        mnUS = new javax.swing.JMenuItem();
        mnVN = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFmTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblFmTitle.setForeground(new java.awt.Color(255, 51, 51));
        lblFmTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFmTitle.setText("Login ");

        btnLanguage.add(rdUS);
        rdUS.setSelected(true);
        rdUS.setText("English");
        rdUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdUSActionPerformed(evt);
            }
        });

        btnLanguage.add(rdVN);
        rdVN.setText("Vietnamese");
        rdVN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdVNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(rdUS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdVN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdUS)
                    .addComponent(rdVN))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("Username");

        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.setEnabled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        cBox.setText("Remember");
        cBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLogin)
                                .addGap(18, 18, 18)
                                .addComponent(btnLogout))
                            .addComponent(cBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cBox)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnLogout))
                .addGap(51, 51, 51))
        );

        tbItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(tbItem);

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Username");

        lblPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPass.setText("Password");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setText("Register Form");

        txtName.setEditable(false);

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirm");
        btnConfirm.setEnabled(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        txtPass.setEditable(false);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        mnFile.setText("File");
        mnFile.setEnabled(false);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        mnFile.add(mnExit);

        mnBar.add(mnFile);

        mnLanguage.setText("Edit");
        mnLanguage.setEnabled(false);

        mnUS.setText("English");
        mnUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUSActionPerformed(evt);
            }
        });
        mnLanguage.add(mnUS);

        mnVN.setText("Vietnamese");
        mnVN.setToolTipText("");
        mnVN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVNActionPerformed(evt);
            }
        });
        mnLanguage.add(mnVN);

        mnBar.add(mnLanguage);

        setJMenuBar(mnBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFmTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(lblPass))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPass)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConfirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblFmTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRegister))
                                .addGap(15, 15, 15)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPass)
                            .addComponent(btnConfirm)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUSActionPerformed

        currentBundle = usBundle;
        display();
     }//GEN-LAST:event_mnUSActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void rdUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdUSActionPerformed

        currentBundle = usBundle;
        display();

    }//GEN-LAST:event_rdUSActionPerformed

    private void rdVNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdVNActionPerformed

        currentBundle = viBundle;
        display();


    }//GEN-LAST:event_rdVNActionPerformed


    private void mnVNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVNActionPerformed

        currentBundle = viBundle;
        display();


    }//GEN-LAST:event_mnVNActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsername.getText().trim();
        String password = txtPassword.getText().trim();
        if (evt.getActionCommand().equals("Login")) {
            if (checkLogin(username, password)) {
                mnFile.setEnabled(true);
                mnLanguage.setEnabled(true);
                JOptionPane.showMessageDialog(this,"Login Successfully");
                btnLogout.setEnabled(true);
                btnLogin.setEnabled(false);
                btnRegister.setEnabled(false);
                txtUsername.setEditable(false);
                txtPassword.setEditable(false);
            } else {
                JOptionPane.showMessageDialog(this,"Username or Password is wrong!");
            }
        }

        if (evt.getActionCommand().equals("Đăng nhập")) {
            if (checkLogin(username, password)) {
                mnFile.setEnabled(true);
                mnLanguage.setEnabled(true);
                JOptionPane.showMessageDialog(this,"Đăng nhập thành công");
                btnLogin.setEnabled(false);
                btnLogout.setEnabled(true);
                btnRegister.setEnabled(false);
                txtUsername.setEditable(false);
                txtPassword.setEditable(false);
            } else {
                JOptionPane.showMessageDialog(this,"Tài khoản hoặc mật khẩu bị sai!");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        if (evt.getActionCommand().equals("Logout")) {
            mnFile.setEnabled(false);
            mnLanguage.setEnabled(false);
            btnLogin.setEnabled(true);
            btnLogout.setEnabled(false);
            btnRegister.setEnabled(true);
            txtUsername.setEditable(true);
            txtPassword.setEditable(true);
            JOptionPane.showMessageDialog(this,"Logout...");
        }

        if (evt.getActionCommand().equals("Đăng xuất")) {
            mnFile.setEnabled(false);
            mnLanguage.setEnabled(false);
            btnLogin.setEnabled(true);
            btnLogout.setEnabled(false);
            btnRegister.setEnabled(true);
            txtUsername.setEditable(true);
            txtPassword.setEditable(true);
            JOptionPane.showMessageDialog(this,"Đăng xuất...");

        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void cBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if (evt.getActionCommand().equals("Register")) {
            txtName.setEditable(true);
            txtPass.setEditable(true);
            txtUsername.setEditable(false);
            txtPassword.setEditable(false);
            btnConfirm.setEnabled(true);
            btnRegister.setEnabled(false);
            insert++;
        }

        if (evt.getActionCommand().equals("Confirm")) {
            if (insert > 0) {
                String username = txtName.getText().trim();
                String password = txtPass.getText().trim();
                try {
                    insert(username, password);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                loadData();
                txtName.setEditable(false);
                txtPass.setEditable(false);
                btnRegister.setText("Register");
                txtUsername.setEditable(true);
                txtPassword.setEditable(true);
                btnRegister.setEnabled(true);
                btnConfirm.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed
    void insert(String username, String password) throws SQLException {
        String query = "insert into user values(?,?)";
        st = cnn.prepareStatement(query);
        st.setString(1, username);
        st.setString(2, password);
        int count = st.executeUpdate();
        if (count == 0) {
            JOptionPane.showMessageDialog(this, "Nothing to save");
        }

    }

    private void loadData() {
        String query = "select * from [user]";
        try {
            st = cnn.prepareStatement(query);
            rs = st.executeQuery();
            model.setRowCount(0);
            while (rs.next()) {
                tmp = new Vector();
                tmp.add(rs.getString(1));
                tmp.add(rs.getString(2));
                model.addRow(tmp);
//                System.out.println(model.getRowCount());
            }
            tbItem.setModel(model);
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex03_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex03_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex03_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex03_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex03_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.ButtonGroup btnLanguage;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox cBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFmTitle;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JMenuBar mnBar;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenu mnLanguage;
    private javax.swing.JMenuItem mnUS;
    private javax.swing.JMenuItem mnVN;
    private javax.swing.JRadioButton rdUS;
    private javax.swing.JRadioButton rdVN;
    private javax.swing.JTable tbItem;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
